### ISSUE TITLE
How can you access this module from `context.app` in plugins?

### ISSUE THREAD

**Issue by Steve525** [nuxt-community/analytics-module#11]
I'm wondering if it's possible to access this module from the `context.app` object passed in on plugin initialization. Not seeing it present.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/analytics-module/issues/c11">#c11</a>)</em></sub></div>

**Comment by Alig96** [comment]
I'm also not seeing it in the context. Need this so I can set my userId via middleware.

**Comment by mohammad-s-git** [comment]
i had the same problem and this is how it works
i wrote the below code in global-scripts.js file which is located inside of plugins directory:

function doSomeThingOnAppMounting(app) {
    if (process.client) {
        app.app.mounted = function() {
           //do whatever you want to be executed in app root vue instance mounted life cycle
        }
    }
}
