### ISSUE TITLE
Can't load tracking code ID as enviroment variables

### ISSUE THREAD

**Issue by stuartjnelson** [nuxt-community/analytics-module#12]
I was hoping to be able to load my tracking code as an environment variable. It seems that the variables on production aren't loaded before the module is initialised. I am deploying with Netlify so I don't know if it's there issue... 

IN this screenshot I am logging;

- Current enviroment
- The tracking code ID from my `.env.production`
- GA debugging is enabled and you can see it's using my development/fallback ID `UA-000000-1`

<img width="742" alt="screen shot 2018-03-24 at 21 05 11" src="https://user-images.githubusercontent.com/5795894/37871635-77513f14-2fa7-11e8-9b26-3b599a8ffc39.png">

**Comment by MatteoGabriele** [comment]
You don't need to put a fake domain id to prevent tracking on development: just use the sendHitTask property and put it to true only for production.

**Comment by stuartjnelson** [comment]
I see. But is it possible to
