### ISSUE TITLE
Update analytics.js to gtag.js

### ISSUE THREAD

**Issue by tvvocold** [nuxt-community/analytics-module#25]
### What problem does this feature solve?

Since Google Analytics has released the gtag.js as the recommended tracking code for new implementations. So please update the codes and docs for analytics module: https://nuxtjs.org/faq/google-analytics

### What does the proposed changes look like?

Check the GA's doc here: https://developers.google.com/analytics/devguides/collection/gtagjs/migration

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/analytics-module/issues/c24">#c24</a>)</em></sub></div>

**Comment by MatteoGabriele** [comment]
Not that easy. It's not just an update, it's more complex than that.

**Comment by MatteoGabriele** [comment]
It has a different API structure so it's not just a feature, it's more a new package or a very very different major version.

**Comment by MatteoGabriele** [comment]
I'll probably go with a major version. I've quite a lot of things done :)

**Comment by ricardogobbosouza** [comment]
Are different modules https://github.com/nuxt-community/google-gtag

**Comment by ricardogobbosouza** [comment]
@MatteoGabriele I think we can close this
