### ISSUE TITLE
Allow ga's id be a function

### ISSUE THREAD

**Issue by raapperez** [nuxt-community/analytics-module#27]
### What problem does this feature solve?

I have a server that is used for different domains. I want to for each domain it uses a different ga id.

### What does the proposed changes look like?

```
{
  modules: [
    // Simple usage
    ['@nuxtjs/google-analytics', {
      id: () => {
        switch (document.domain) {
          case 'github.com':
            return 'UA-12301-2';
          case 'foo.com':
            return 'UA-12301-3';
          default:
            return 'UA-12301-4';
        }
      }
    }]
 ]
}
```

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/analytics-module/issues/c28">#c28</a>)</em></sub></div>

**Comment by CKGrafico** [comment]
Must have!

**Comment by CKGrafico** [comment]
Seems that this is supported by the plugin in behind, let me check https://github.com/MatteoGabriele/vue-analytics/blob/8fddca1bbb4edd422931fac94bb7b7fc5e5ca5b9/docs/installation.md

**Comment by MatteoGabriele** [comment]
this is already possible indeed: string, array of strings, functions and promises are already supported.
