### ISSUE TITLE
Cacheable Option or Async analytics

### ISSUE THREAD

**Issue by jericopulvera** [nuxt-community/analytics-module#29]
### What problem does this feature solve?

pagespeed insight optimization suggestion.

### What does the proposed changes look like?

It would swap out analytics js to galite when cache: true

Just thought that it would be a good idea to have this in main analytics module of nuxt. 

Thanks

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/analytics-module/issues/c31">#c31</a>)</em></sub></div>

**Comment by equinusocio** [comment]
@MatteoGabriele Hi, any update on this?

**Comment by MatteoGabriele** [comment]
you could create a ternary statement in the using the `customResourceURL` property.

something like:

```js
{
  customResourceURL: cached ? 'foo.js' : 'bar.js'
}
```

**Comment by ricardogobbosouza** [comment]
@MatteoGabriele I think we can close this
