### ISSUE TITLE
Run only in production mode

### ISSUE THREAD

**Issue by cryptomaniac512** [nuxt-community/analytics-module#4]
Can you provide some option or disable it by default for non-production mode?

**Comment by MatteoGabriele** [comment]
@cryptomaniac512 you can avoid analytics to send data during development, just by setting the `debug.sendHitTask` property to `false` ( check [debug](https://github.com/MatteoGabriele/vue-analytics/blob/master/docs/debug.md) page )

**Comment by cryptomaniac512** [comment]
How can I set `sendHitTask` to false only if project not in production mode? With this option analytics doesn't work when I run `generate`.

**Comment by bjunc** [comment]
@cryptomaniac512 (and for anyone else who stops by), this is how I ensure tracking events are only sent to GA in production:

```js
// nuxt.config.js
const isProd = process.env.NODE_ENV === 'production'
module.exports = {
  modules: [
    ['@nuxtjs/google-analytics', { id: 'UA-XXXXXX', debug: { sendHitTask: isProd } }]
  ]
}
```

I use the `isProd` const elsewhere in the config (proxies, API urls, etc.).

@MatteoGabriele this might be worth documenting in the main README, as it's a very common (if not certain) configuration consideration.

**Comment by MatteoGabriele** [comment]
@bjunc Thanks for sharing this. 
To be honest I gave this for granted, but I might gonna add an example right in the Debug section.

Thanks
