### ISSUE TITLE
Programmatically enabling/disabling not working

### ISSUE THREAD

**Issue by josh-king** [nuxt-community/analytics-module#49]
### Version

[1](https://github.com/analytics-module/releases/tag/1)

### Reproduction link

https://codesandbox.io/s/kor57z1vy7

(Please use the extension _Google Tag Manager_ to view the tag)

### Steps to reproduce

Whenever you try to programmatically fire the $ga.enable/$ga.disable the tracking is still active

### What is expected ?

That specific user should be disabled from being tracked in the real time tracking

### What is actually happening?

The calls don't seem to do anything, they are initialized but not functioning.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/analytics-module/issues/c36">#c36</a>)</em></sub></div>

**Comment by josh-king** [comment]
Added codesandbox

**Comment by ricardogobbosouza** [comment]
@josh-king to disable or enable https://matteogabriele.gitbooks.io/vue-analytics/content/docs/opt-out.html

Try this:
```js
export default {
  methods: {
    disableTracking () {
      this.$ga.disable()
      // from now on analytics is disabled
    },
    enableTracking () {
      this.$ga.enable()
      // from now on analytics is enabled
    }
  }
}
```

**Comment by josh-king** [comment]
@ricardogobbosouza Unfortunately when I used the disable-tracking method the user is still being tracked.

**Comment by ricardogobbosouza** [comment]
Hi @josh-king 
I can not reproduce your issue.
What version of `nuxt` and the `analytics-module` are you using?

**Comment by ricardogobbosouza** [comment]
This simple example works perfectly:

```js
// nuxt.config.js
export default {
    modules: [
        ['@nuxtjs/google-analytics', {
            id: 'UA-AAA',
            debug: {
                enabled: true,
                sendHitTask: true
            }
        }]
    ]
}
```

```vue
// pages/index.vue
<template>
    <div>
        <button @click="enableTracking">Enable</button>
        <button @click="disableTracking">Disable</button>
        <button @click="eventTrack">Event track</button>
    </div>
</template>

<script>
    export default {
        methods: {
            disableTracking () {
                this.$ga.disable()
            },
            enableTracking () {
                this.$ga.enable()
            },
            eventTrack() {
                this.$ga.event('category', 'action', 'label', 123)
            }
        }
    }
</script>
```

**Comment by manniL** [comment]
@josh-king 	It won't "unload the script" so indications in script blockers will still exist. But nevertheless, the code works.
