### ISSUE TITLE
Analytics not loading and disabling css module

### ISSUE THREAD

**Issue by sebastianmarines** [nuxt-community/analytics-module#52]
### Version

[2.2.0](https://github.com/analytics-module/releases/tag/2.2.0)

### Reproduction link

[https://github.com/sebastianmarines/maz/](https://github.com/sebastianmarines/maz/)

### Steps to reproduce

Install google analytics
```
yarn install @nuxtjs/google-analytics
```
Add module to nuxt.config.js
```javascript
modules: [
    '@nuxtjs/bulma',
    ['@nuxtjs/google-analytics', {
       id: 'UA-12301-2'
     }]
  ],

```

### What is expected ?

Analytics module should load

### What is actually happening?

The css module is being blocked from loading and the analytics module is not loading

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/analytics-module/issues/c38">#c38</a>)</em></sub></div>

**Comment by manniL** [comment]
Please add a reproduction.

**Comment by robyedlin** [comment]
@sebastianmarines The issue may be that the GA id is not loaded in. Check your console log and see. If there's a vue-analytics error, the rest of your js will likely be broken.

**Comment by robyedlin** [comment]
@sebastianmarines Make sure that your google analytics code is a string. It **should** be `'UA-XXXXXXX-XX'` not `UA-XXXXXXX-XX`
