### ISSUE TITLE
How do you even start this?

### ISSUE THREAD

**Issue by jericopulvera** [nuxt-community/analytics-module#7]
followed the instructions and this happens.

I also did npm install vue-analytics

 ERROR  Nuxt error

  Error: Cannot resolve "@nuxtjs/google-analytics" from "/home/jerico/public_html/jerico.xyz/client/nuxtjs/google-analytics"
  
  - nuxt.js:220 Nuxt.resolvePath
    [jerico.xyz]/[nuxt]/lib/core/nuxt.js:220:11
  
  - module.js:114 ModuleContainer.addModule
    [jerico.xyz]/[nuxt]/lib/core/module.js:114:35
  
  - utils.js:96 promise.then
    [jerico.xyz]/[nuxt]/lib/common/utils.js:96:43
  
  
  - next_tick.js:188 process._tickCallback
    internal/process/next_tick.js:188:7
  
  - module.js:686 Function.Module.runMain
    module.js:686:11
  
  - bootstrap_node.js:187 startup
    bootstrap_node.js:187:16
  
  - bootstrap_node.js:608

**Comment by pi0** [comment]
Hey. It seems `@nuxtjs/google-analytics` package is not probably installed. We use it in some production apps ;)

**Comment by jericopulvera** [comment]
How to install?
Npm install @nuxtjs/google-analytics?

**Comment by MatteoGabriele** [comment]
@jericopulvera this is taken from the setup in the Readme file 

> Add  `@nuxtjs/google-analytics` dependency using yarn or npm to your project

So yes, you need to run `yarn add @nuxtjs/google-analytics`, which is the nuxt wrapper of `vue-analytics`, and follow the nuxt plugins installation process.

After that, for every options or API reference you can refer to [vue-analytics](https://github.com/MatteoGabriele/vue-analytics)
