### ISSUE TITLE
Nuxt Analytics multiples IDs

### ISSUE THREAD

**Issue by rafahill** [nuxt-community/analytics-module#74]
Hello! i have some issue to add an aditional ID in a specific page:

> **My Nuxt.config.js
> modules: [
>     ['@nuxtjs/google-analytics', { id: 'UA-XXXX-X' }],
>   ],**

Work as expected, tracking my pages.

But in a specific page i need to add another ID.
i already try to use all methods that i find in docs, but its doesn work for me

**> My method in a specific page:
> import VueAnalytics from 'vue-analytics'
> import Vue from 'vue'
> 
> startGoogleAnalytics () {
>       let gaCode = 'UA-' + this.event.google_analytics
>       Vue.use(VueAnalytics, {
>         id: gaCode
>  })**

im also try to use set option like:
this.$ga.set('userID', xxxxx)

but still not work for me

Could someone help me?
Thanks

**Comment by ricardogobbosouza** [comment]
Hi @rafahill 
Try nuxt option [`asyncID`](https://github.com/nuxt-community/analytics-module/blob/master/lib/plugin.js#L7):

```js
export default {
  buildModules: [
    '@nuxtjs/google-analytics'
  ],
  googleAnalytics: {
    asyncID(ctx) {
      return ctx.app.router.name === 'index' ? 'UA-XXXX' : 'UA-YYYY'
    }
  }
}
```

**Comment by drewbaker** [comment]
Is it possible to track to two different accounts? Often times a client wants their own ID and we like to have ours to monitor as well.
