### ISSUE TITLE
Nuxt Analytics not working when building with yarn generate

### ISSUE THREAD

**Issue by termorrell** [nuxt-community/analytics-module#79]
### Version

[2.3.0](https://github.com/analytics-module/releases/tag/2.3.0)

### Reproduction link

[https://gist.github.com/termorrell/72a2c6f3a8dc926c7c46953e57f1ca94](https://gist.github.com/termorrell/72a2c6f3a8dc926c7c46953e57f1ca94)

### Steps to reproduce

I have added the analytics module following the documentation in the README.

```
export default {
...
buildModules: [
    ['@nuxtjs/google-analytics', {
      id: 'UA-********-**'
    }],
  ],
...
}
``` 

Running when running `yarn generate` I cannot see any events firing to Google Analytics. This is also the case when adding the `debug: enabled` flag to `true`.

### What is expected ?

When building the site with `yarn generate` I would expect to see the events firing to Google Analytics.

### What is actually happening?

No events are being fired. I can see my GA ID in the compiled Nuxt JS but they are not appearing in network requests and not appearing in the GA dashboard.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/analytics-module/issues/c60">#c60</a>)</em></sub></div>

**Comment by garySiladi** [comment]
Try to move the dependency from dev dependency to normal one.

**Comment by nonlinearcom** [comment]
This isn't working for me neither... is there any other workaround?
